import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const { itemName, prompt } = await req.json();

    if (!itemName && !prompt) {
      return NextResponse.json({ error: "itemName or prompt is required" }, { status: 400 });
    }

    const defaultPrompt = `A single, minimalist, cute line-drawing icon of a ${itemName}, designed as a physical bullet journal rubber stamp. Thick, clean black outlines on a pure white background. Flat vector graphic style, entirely 2D, no shading, no intricate details, no gradients. Absolutely no square borders or frames drawn around the object. The ${itemName} should be centered with clear negative space.`;
    
    const promptText = prompt ? prompt.replace(/\${itemName}/g, itemName || "") : defaultPrompt;

    const apiKey = process.env.VERTEX_AI_API_KEY;

    if (!apiKey) {
      console.warn("VERTEX_AI_API_KEY is not set. Using a mock response.");
      return NextResponse.json({
        image: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=",
        mock: true
      });
    }

    // Using the user-verified direct REST API payload for the `gemini-3-pro-image-preview` model via API Key on aiplatform
    const API_ENDPOINT = "aiplatform.googleapis.com";
    const MODEL_ID = "gemini-3-pro-image-preview";
    const GENERATE_CONTENT_API = "streamGenerateContent";
    const url = `https://${API_ENDPOINT}/v1/publishers/google/models/${MODEL_ID}:${GENERATE_CONTENT_API}?key=${apiKey}`;

    const requestBody = {
      contents: [
        {
          role: "user",
          parts: [{ text: promptText }]
        }
      ],
      generationConfig: {
        temperature: 1,
        maxOutputTokens: 32768,
        responseModalities: ["TEXT", "IMAGE"],
        topP: 0.95,
        imageConfig: {
          aspectRatio: "1:1",
          imageSize: "1K",
          imageOutputOptions: {
            mimeType: "image/png"
          },
          personGeneration: "ALLOW_ALL"
        }
      },
      safetySettings: [
        { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "OFF" },
        { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "OFF" },
        { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "OFF" },
        { category: "HARM_CATEGORY_HARASSMENT", threshold: "OFF" }
      ]
    };

    const response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(requestBody)
    });

    const data = await response.json();

    if (!response.ok) {
      console.error("Vertex AI Direct API Error:", JSON.stringify(data, null, 2));
      throw new Error(data.error?.message || "Failed to generate image from Direct API.");
    }

    // streamGenerateContent returns an array of response objects
    let base64Image = null;

    if (Array.isArray(data)) {
      for (const chunk of data) {
        const parts = chunk.candidates?.[0]?.content?.parts || [];
        for (const part of parts) {
          if (part.inlineData && part.inlineData.data) {
            base64Image = part.inlineData.data;
            break;
          }
        }
        if (base64Image) break;
      }
    } else if (data.candidates) {
      // Fallback in case endpoint returns non-stream format unexpectedly
      const parts = data.candidates[0]?.content?.parts || [];
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          base64Image = part.inlineData.data;
          break;
        }
      }
    }

    if (base64Image) {
      return NextResponse.json({ image: base64Image });
    } else {
      console.error("No image found in predictions structure:", JSON.stringify(data));
      throw new Error("No image generated by the API.");
    }

  } catch (error: any) {
    console.error("Error generating image:", error);
    return NextResponse.json({ error: error.message || "Failed to generate image" }, { status: 500 });
  }
}
